### ISSUE TITLE
Change Listener

### ISSUE THREAD

**Issue by Sharj** [fiskurgit/ChipCloud#1]
Hi,

First of all thank you for the library.

I was going to use the library but I noticed `chipListener` has only `chipSelected` method.  `chipSelected` will not be called in case user deselects already selected chip and it seems like we don't have a way to know if a chip is selected anymore in this case. Is there anyway to find that?

**Comment by fiskurgit** [comment]
Sure, give me a few hours to tidy up the repository - a couple of bad design decisions are in this thing I want to fix too. It's an older project but Android Arsenal just picked it up so it's getting a bit of use.

**Comment by fiskurgit** [comment]
Okay, have pushed version 2.0.3 which fixes some issues and adds ```chipDeselected(int index);``` to the interface.
