### ISSUE TITLE
Unable to import via gradle

### ISSUE THREAD

**Issue by larrytech7** [fiskurgit/ChipCloud#10]
i'm trying to import as this: compile 'com.github.fiskurgit:ChipCloud:2.1.0@aar'
or compile 'com.github.fiskurgit:ChipCloud:2.1.0' 
but it fails and says, failed to resolve the library. Any way in which i should do?

**Comment by fiskurgit** [comment]
May have been a temporary problem with Jitpack or your own network.  Is it still a problem?

**Comment by larrytech7** [comment]
Yes it still is. anyway I've just moved on with another library. thanks

**Comment by deeman30rus** [comment]
I had similar problem and this helped me 
https://stackoverflow.com/questions/33058358/jitpack-io-failed-to-resolve-github-repo
