### ISSUE TITLE
How to get selected chips list

### ISSUE THREAD

**Issue by prashanthd** [fiskurgit/ChipCloud#11]
Hi,
How to get selected chips list? Am I need to maintain a list separately? In that list add  selected chips?

**Comment by fiskurgit** [comment]
Yes. there seems to be some confusion about how this library is intended to be used, it's strictly a UI tool, you build the display chips from some array - then you use chipSelected and chipDeselected to update your model. You shouldn't expect a UI component like this to keep track of your app state.

**Comment by fiskurgit** [comment]
Added a convenience method to do this:

```
Integer[] selectedChips = chipCloud.getSelectedIndexes();
for(Integer i : selectedChips){
  Log.d(TAG, "Selected chip: " + i);
}
```

**Comment by RahulSDeshpande** [comment]
Heyy @fiskurgit, I couldn't find the below method which you have said you have added in the library since v2.2.2 !!
```
chipCloud.getSelectedIndexes();
```

Could you please help me.

**Comment by john990** [comment]
My solution：

`public class TagCloudView extends ChipCloud {
    private ViewGroup layout;

    public TagCloudView(Context context, ViewGroup layout, ChipCloudConfig config) {
        super(context, layout, config);
        this.layout = layout;
    }

    public List<Integer> getSelectedTagIndex() {
        List<Integer> index = new ArrayList<>();
        for (int i = 0; i < layout.getChildCount(); i++) {
            ToggleChip chip = (ToggleChip) this.layout.getChildAt(i);
            if (chip.isChecked()) {
                index.add(i);
            }
        }
        return index;
    }

    private int getIndexByView(View view) {
        for (int i = 0; i < layout.getChildCount(); i++) {
            View child = this.layout.getChildAt(i);
            if (child == view) {
                return i;
            }
        }
        return -1;
    }

    private boolean keepLastOneCheck(View view) {
        List<Integer> selectedTagIndex = getSelectedTagIndex();
        return !(selectedTagIndex.size() == 1 && selectedTagIndex.contains(getIndexByView(view)));
    }

    @Override
    public void onClick(View view) {
        if (!keepLastOneCheck(view)) {
            return;
        }
        super.onClick(view);
    }
}`

**Comment by RahulSDeshpande** [comment]
Good workaround :)
