### ISSUE TITLE
Mode.NONE is not existing in maven

### ISSUE THREAD

**Issue by marcosPerezRubio** [fiskurgit/ChipCloud#13]
Almost self explanatory, the module downloaded from maven doesn't have the NONE option in the enumeration.

**Comment by fiskurgit** [comment]
Will add this tomorrow, think I just forgot to push a tag after merging the last pull request, in the meanwhile you can just reference a local copy of the project.

**Comment by fiskurgit** [comment]
@marcosPerezRubio k, try with version 2.1.1 - first run may take a few minutes while jitpack checkout and build the artefact.
