### ISSUE TITLE
Single line like Play store category

### ISSUE THREAD

**Issue by pong106** [fiskurgit/ChipCloud#14]
Any idea on how to present the ChipCloud items in a line and scrollable if when needed. I tried with HorizontalScrollView. Result is the ChipCloud is not wrapping the width. 

HorizontalScrollView -width -> wrap_content or match_parent
Chipcloud -width -> wrap_content or match_parent

**Comment by fiskurgit** [comment]
With the new version of the library you supply the ViewGroup that contains the chips, so you should be able to use a HorizontalScrollView
