### ISSUE TITLE
How to unselect a chip programetically

### ISSUE THREAD

**Issue by tejpratap46** [fiskurgit/ChipCloud#17]
There is a method `chipCloud.setSelectedChip(index)` but there is no method `chipCloud.setUnSelectedChip(index)`

I tried,
`chipCloud.getViewAt(index).setSelected(false); // not working`
`chipCloud.chipDeselected(index) // not working`

Please give more documentation.

**Comment by fiskurgit** [comment]
Sorry for delay, method added in 2.2.3:

```
chipCloud.deselectChip(someIndex);
```
