### ISSUE TITLE
More Config for Chips UI

### ISSUE THREAD

**Issue by CeJienAJPC** [fiskurgit/ChipCloud#22]
Thank you for the plain integration using Google FlexBoxLayout.

It would be awesome if it is possible to tweak the Chip UIs with parameters like Corner Radius, Text Size and Padding

Thanks

**Comment by fiskurgit** [comment]
Have added a config option in 3.0.3 useInsetPadding that will add padding to the chips so they can be easily used in any layout (I'd only developed with FlexboxLayout in mind previously, but while creating a HorizontalScrollView example realised the need for padding on the Chips).

I can't add CornerRadius and TextSize as I'm trying to stick to the Material Design Chip guidelines: https://material.io/guidelines/components/chips.html#chips-specs
