### ISSUE TITLE
How to define space between each Row of Chips

### ISSUE THREAD

**Issue by CeJienAJPC** [fiskurgit/ChipCloud#23]
I am trying to display the Chips inside FlexBoxLayout with layout_height="wrap_content". When using wrap_content in FlexBoxLayout, the Chips are getting organized without inter-row spaces. Is it possible to introduce Blank spaces between rows when using wrap_content?

Thanks

**Comment by fiskurgit** [comment]
You need to define a dividerDrawable on your Flexbox:

https://github.com/fiskurgit/ChipCloud/blob/master/demo/src/main/res/layout/activity_demo.xml#L24

https://github.com/fiskurgit/ChipCloud/blob/master/demo/src/main/res/drawable/div.xml

**Comment by fiskurgit** [comment]
As mentioned in other ticket - as of 3.0.3 you can now also do useInsetPadding = true on the config builder.

**Comment by daswanihimanshu010** [comment]
<com.google.android.flexbox.FlexboxLayout
                    android:id="@+id/flexbox"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:justifyContent="space_around"
                    app:alignContent="flex_start"
                    app:alignItems="flex_start"
                    android:visibility="gone"
                    app:flexWrap="wrap"
                    android:padding="10dp"
                    />

A better solution
