### ISSUE TITLE
Multi-Select

### ISSUE THREAD

**Issue by austinhodak** [fiskurgit/ChipCloud#3]
Would love to see the ability to select multiple chips! Thanks!

**Comment by fiskurgit** [comment]
Yeah, that should be a feature - I'll get on it.

**Comment by fiskurgit** [comment]
Added in 2.0.4 use ```singleChoice(false)``` in the config builder, ```setSingleChoice(false);``` on the chipcloud, or ```chipcloud:singleChoice="false"``` in XML.
