### ISSUE TITLE
Null Object

### ISSUE THREAD

**Issue by coolmyll** [fiskurgit/ChipCloud#32]
`java.lang.NullPointerException: Attempt to read from field 'boolean fisk.chipcloud.ChipCloudConfig.useInsetPadding' on a null object reference`

I have the flexlayout inside a dialog. How can i set the chipcloud object without getting a null object error?
Here is my code:
`FlexboxLayout flexbox = (FlexboxLayout) dialog.findViewById(R.id.flexbox);

ChipCloud chipCloud = new ChipCloud(dialog.getContext(), flexbox);

chipCloud.addChip("HelloWorld!");`

**Comment by daniel0x7CC** [comment]
that's a bug that I noticed too. It happens because you did not start ChipCloudConfig.

ChipCloudConfig config = new ChipCloudConfig()
    .selectMode(ChipCloud.SelectMode.multi)
    .checkedChipColor(Color.parseColor("#ddaa00"))
    .checkedTextColor(Color.parseColor("#ffffff"))
    .uncheckedChipColor(Color.parseColor("#efefef"))
    .uncheckedTextColor(Color.parseColor("#666666"))
    .useInsetPadding(true)
    .typeface(someCustomeTypeface);

ChipCloud chipCloud = new ChipCloud(this, flexbox, config);

**Comment by coolmyll** [comment]
Yep seems like config is necessary even if no customization is needed.
