### ISSUE TITLE
I want to increase the height of each chip.

### ISSUE THREAD

**Issue by mrkamiali** [fiskurgit/ChipCloud#38]
please let me know if there's any solution to my problem.
Thanks..

**Comment by 97balakrishnan** [comment]
Yeah it would be nice if it was possible to manually set width and height of chips.

**Comment by Fahad-pnw** [comment]
if you put the library in your own project, in chipcloud class
you can change height.
i believe you can put parameters too but anyway, here's how you do it


public <T> void addChip(T object, Drawable drawable, boolean resizeDrawable){
    ToggleChip toggleChip;
    int chipHeight;
    if(config.useInsetPadding){
      toggleChip = (ToggleChip) LayoutInflater.from(context).inflate(R.layout.inset_toggle_chip, layout, false);
      chipHeight = context.getResources().getDimensionPixelSize(R.dimen.inset_chip_height);
    }else{
      toggleChip = (ToggleChip) LayoutInflater.from(context).inflate(R.layout.toggle_chip, layout, false);
      chipHeight = context.getResources().getDimensionPixelSize(R.dimen.chip_height);
    }
    toggleChip.setLabel(object.toString());
    ConfigHelper.initialise(toggleChip, config);

    if(drawable != null){
      if(resizeDrawable) {
        toggleChip.setDrawable(context, drawable);
      }else{
        toggleChip.setDrawableNoResize(context, drawable);
      }
    }

    if(config.selectMode == SelectMode.close){
      if(closeX == null){
        closeX = ConfigHelper.closeDrawable(context, config.closeTint);
      }
      toggleChip.showClose(closeX);
    }
    toggleChip.setHeight(chipHeight);
    toggleChip.setOnClickListener(this);


    layout.addView(toggleChip);
  }

**Comment by mrkamiali** [comment]
I have use this library couple a months ago ... but thanks for the reply.
