### ISSUE TITLE
No margin or padding on API 19

### ISSUE THREAD

**Issue by ThunderRoid** [fiskurgit/ChipCloud#4]
No margin or padding on API 19 (KITKAT), works good with API 21 and 23, haven't tested on other APIs.
Please fix.
Thank you so much for creating such a great library.

![device-2016-07-02-154402](https://cloud.githubusercontent.com/assets/3328263/16539690/9c6306ec-406c-11e6-9f43-0f3329b1b562.png)

**Comment by fiskurgit** [comment]
I'll have a look at this over the next few days, attempting to replicate it now

**Comment by fiskurgit** [comment]
Looks like there's a problem on KitKat when using ```setBackgroundCompat()``` with a TransitionDrawable, have a fix already, should be ready within an hour.

**Comment by fiskurgit** [comment]
Fixed in 2.0.5 - let me know if you have any trouble.
<img width="270" alt="screen shot 2016-07-03 at 15 33 16" src="https://cloud.githubusercontent.com/assets/5167046/16546013/67d4af52-4134-11e6-8839-995353a92b2d.png">

**Comment by ThunderRoid** [comment]
Thanks again
