### ISSUE TITLE
Read Value from a Chip

### ISSUE THREAD

**Issue by vptcr** [fiskurgit/ChipCloud#7]
Thanks for the useful library. How can one read the value (label/text) of a Chip?
something like :- chipCloud.getChildAt(index).get<xxx>

**Comment by fiskurgit** [comment]
You can just use `chipSelected` and `chipDeselected` in ChipListener, or use `isSelected(int index)` to get the value from the array you built the ChipCloud with.

**Comment by kyndaqtepammy** [comment]
I cannot find any of these methods
